BronzongLakeWest_Frlg_MapScripts::
	.byte 0


BronzongLake_EventScript_CodyBattle::
# 10 "data/maps/BronzongLakeWest_Frlg/scripts.pory"
	trainerbattle_single TRAINER_FISHERBOY_CODY, BronzongLake_EventScript_CodyBattle_Text_0, BronzongLake_EventScript_CodyBattle_Text_1
# 11 "data/maps/BronzongLakeWest_Frlg/scripts.pory"
	release
	return


BronzongLake_EventScript_CodyBattle_Text_0:
# 10 "data/maps/BronzongLakeWest_Frlg/scripts.pory"
	.string "YO!$"

BronzongLake_EventScript_CodyBattle_Text_1:
# 10 "data/maps/BronzongLakeWest_Frlg/scripts.pory"
	.string "Aw man!$"
