ShaydwellTown_CodysHouse_1F_Frlg_MapScripts::
	.byte 0


ShaydwellTown_CodysHouse_1F_CodyMom::
# 5 "data/maps/ShaydwellTown_CodysHouse_1F_Frlg/scripts.pory"
	lock
# 6 "data/maps/ShaydwellTown_CodysHouse_1F_Frlg/scripts.pory"
	faceplayer
# 7 "data/maps/ShaydwellTown_CodysHouse_1F_Frlg/scripts.pory"
	msgbox ShaydwellTown_CodysHouse_1F_CodyMom_Text_0
# 8 "data/maps/ShaydwellTown_CodysHouse_1F_Frlg/scripts.pory"
	release
	return


ShaydwellTown_CodysHouse_1F_CodyMom_Text_0:
# 7 "data/maps/ShaydwellTown_CodysHouse_1F_Frlg/scripts.pory"
	.string "Hm? Cody? He's fishing down at Bronzong\n"
	.string "Lake.\p"
	.string "That boy is always outside!$"
